# Generated by Django 4.2.7 on 2023-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_alter_customer_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="contact_name",
            field=models.CharField(max_length=128),
        ),
    ]
