# Generated by Django 4.2.7 on 2023-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_billing_address_alter_customer_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='role',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
