# Generated by Django 4.2.7 on 2023-12-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='VAT Number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
