# Generated by Django 4.2.7 on 2023-12-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_customer_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="CK Number",
            field=models.CharField(default="", max_length=32),
        ),
    ]
