# Generated by Django 4.2.7 on 2023-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0017_alter_customer_suspend_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="suspend_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
