# Generated by Django 4.2.7 on 2023-12-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0018_alter_customer_suspend_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="active",
        ),
        migrations.AddField(
            model_name="customer",
            name="suspend",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="CK Number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="customer",
            name="VAT Number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="suspend_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
