# Generated by Django 4.2.7 on 2024-01-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_customer_customer_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='customer',
            new_name='customer_number',
        ),
    ]
