# Generated by Django 4.2.7 on 2023-12-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('reference_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryquote')),
            ],
        ),
    ]
