# Generated by Django 4.2.7 on 2023-12-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryquoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryquoteitem',
            name='reference_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryquote'),
        ),
    ]
