# Generated by Django 4.2.7 on 2023-12-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_reference_number_inventoryquoteitem_inventory_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryquoteitem',
            name='quantity',
        ),
    ]
