# Generated by Django 4.2.7 on 2023-12-27 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0006_remove_inventoryquoteitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryquoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "reference_number",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
