# Generated by Django 4.2.7 on 2023-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_price_purchaseorderitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
