# Generated by Django 4.2.7 on 2024-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_purchaseorderitem_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=16
            ),
        ),
    ]
