# Generated by Django 4.2.7 on 2024-02-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_purchaseorder_invoice_number_purchaseorder_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manual_prices",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="inventory.product",
            ),
        ),
    ]
