# Generated by Django 4.2.7 on 2024-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_options'),
        ('inventory', '0020_rename_item_number_productsupplieritem_supplier_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_numbers', to='suppliers.supplier'),
        ),
    ]
