# Generated by Django 4.2.7 on 2024-05-02 13:11

import common.abstract.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_alter_contactperson_id'),
        ('inventory', '0023_alter_inventoryquote_reference_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('reference_number', common.abstract.fields.ReferenceNumberField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('credit_number', models.IntegerField(default=1, editable=False, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('memo', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice', to_field='invoice_number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
