# Generated by Django 4.2.7 on 2023-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
