# Generated by Django 4.2.7 on 2024-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='physical_address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
